---
title: "Onset of Labor analysis drug assay"
output: html_document
date: '2023-01-31'
---

```{r setup, include=FALSE}
setwd("/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis")

library(tidyverse)
library(tidyselect)
library(reshape2)
library(dplyr)
library(pheatmap)
library(RColorBrewer)
library(viridis)
library(paletteer)
library(readxl)
library(tidyr)

funct_path = "/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis/Onset of Labor Study Reanalysis PTB drug assay matching gates.csv"
out_path = "/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis"
```

```{r}
MyData = read.csv(funct_path)
MyData= MyData %>% rename("stimulation" = "Stims") %>% 
  dplyr::mutate(ID = paste0("P",ID, "_", GA)) 
  
MyData = MyData[MyData$ID != "Pinternalcontrol_na", ]
    
unique(MyData$ID)
final_data = c()
fil = setdiff(colnames(MyData), c("stimulation", "median", "EGA", "GA", "DOS"))
MyData$ID = as.character(MyData$ID)
MyData = subset(MyData, select = -c(EGA, GA, DOS))

for(timepoint in unique(MyData$ID)){
  
  MyData_timepoint = MyData %>% 
    filter(ID == timepoint) 
  
  stims = unique(MyData_timepoint$stimulation) 
  
  MyData_timepoint = MyData_timepoint %>% 
    mutate(feature = asinh(median/5))
    
    MyData_timepoint = MyData_timepoint[, names(MyData_timepoint) != "median"] %>%
    pivot_wider(names_from = stimulation, values_from = feature)
  
  for (stim in stims){
    if (stim!="unstim"){
      MyData_timepoint[stim] = MyData_timepoint[stim] - MyData_timepoint["unstim"]
    }
  }
  
  MyData_fin = MyData_timepoint %>% 
    pivot_longer(-all_of(fil),
                 names_to="stimulation",values_to="feature")
  
  final_data = rbind(final_data, MyData_fin)
  
}
write.csv(final_data, paste(out_path, "preprocessed_OOL.csv", sep = "/"))
```

```{r}
x = final_data[!grepl("pp", final_data$ID),] %>%
  dcast(ID ~ population + reagent + stimulation, value.var = "feature")

TTL = read.csv(funct_path)
TTL= TTL %>% rename("stimulation" = "Stims") %>% 
  dplyr::mutate(ID = paste0("P",ID, "_", GA)) 
TTL = TTL[TTL$ID != "Pinternalcontrol_na", ]
TTL = subset(TTL, select = c(EGA, DOS, ID))
TTL = TTL[!grepl("pp", TTL$ID),]
TTL = TTL %>% group_by(ID) %>% 
  filter(row_number()==1)

im_noEGA = x
im_EGA = cbind(x, TTL$EGA)
write.csv(im_noEGA, paste(out_path, "immunome_noEGA_OOL.csv", sep = "/"))
write.csv(im_EGA, paste(out_path, "immunome_EGA_OOL.csv", sep = "/"))

DOS = subset(TTL, select = c(DOS, ID))
write.csv(DOS, paste(out_path, "outcome_OOL.csv", sep = "/"))
```


```{r}
penalization_IFNa = read_xlsx("/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis/penalization matrix drug assay.xlsx", sheet = "IFNa")
penalization_IFNa = penalization_IFNa[1:12]
colnames(penalization_IFNa)[1] <- "population"
as.factor(penalization_IFNa$population)
penalization_IFNa = gather(penalization_IFNa, "protein", "penalization", -population)
penalization_IFNa = penalization_IFNa %>% mutate(feature = paste0(population, "_",protein, "_IFNa")) %>% subset(penalization_IFNa$penalization == 0)

penalization_LPS = read_xlsx("/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis/penalization matrix drug assay.xlsx", sheet = "LPS")
penalization_LPS = penalization_LPS[1:12]
colnames(penalization_LPS)[1] <- "population"
as.factor(penalization_LPS$population)
penalization_LPS = gather(penalization_LPS, "protein", "penalization", -population)
penalization_LPS = penalization_LPS %>% mutate(feature = paste0(population, "_",protein, "_LPS")) %>% subset(penalization_LPS$penalization == 0)

penalization_IL246 = read_xlsx("/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis/penalization matrix drug assay.xlsx", sheet = "IL246")
penalization_IL246 = penalization_IL246[1:12]
colnames(penalization_IL246)[1] <- "population"
as.factor(penalization_IL246$population)
penalization_IL246 = gather(penalization_IL246, "protein", "penalization", -population)
penalization_IL246 = penalization_IL246 %>% mutate(feature = paste0(population, "_",protein, "_IL246")) %>% subset(penalization_IL246$penalization == 0)

penalization_GMCSF = read_xlsx("/Users/jeinhaus/Library/Mobile Documents/com~apple~CloudDocs/Documents/Stanford PostDoc/05 Drug Assay Preterm Birth/R analysis/penalization matrix drug assay.xlsx", sheet = "GMCSF")
penalization_GMCSF = penalization_GMCSF[1:12]
colnames(penalization_GMCSF)[1] <- "population"
as.factor(penalization_GMCSF$population)
penalization_GMCSF = gather(penalization_GMCSF, "protein", "penalization", -population)
penalization_GMCSF = penalization_GMCSF %>% mutate(feature = paste0(population, "_",protein, "_GMCSF")) %>% subset(penalization_GMCSF$penalization == 0)

penalization = rbind(penalization_LPS,penalization_IL246,penalization_IFNa,penalization_GMCSF)
discard <- penalization$feature
names.use <- names(im_noEGA)[!(names(im_noEGA) %in% discard)]
im_noEGA_pen  <- im_noEGA[, names.use]

names.use <- names(im_EGA)[!(names(im_EGA) %in% discard)]
im_EGA_pen  <- im_EGA[, names.use]
write.csv(im_noEGA_pen, paste(out_path, "immunome_noEGA_pen_OOL.csv", sep = "/"))
write.csv(im_EGA_pen, paste(out_path, "immunome_EGA_pen_OOL.csv", sep = "/"))
```

```{r}
featuretable <- read.csv("/Users/jeinhaus/Downloads/Results Reanalysis_OOL_for_PTB_assay_without_EGA[22]/Multivariate Results/immunome_noEGA_pen_OOL/STABL_selection_Reanalysis_OOL_for_PTB_assay_without_EGA_immunome_noEGA_pen_OOL/Max STABL scores.csv")
colnames(featuretable)[1] <- "feature"
featuretable0_2 <- featuretable[1:18,]
modelfeatures <- featuretable0_2$feature
features.use <- names(im_noEGA)[(names(im_noEGA) %in% modelfeatures)]
model0_2 <- im_noEGA[, features.use]
model0_2 <- cbind(model0_2, TTL$DOS)
colnames(model0_2)[19] <- "DOS"

lm0_2 = lm(DOS~model0_2[1:18], data = model0_2) #Create the linear regression
summary(lm0_2) #Review the results
```


