def import_lib(fpy):
    """
    Import the necessary libraries to run any stabl pipeline 
    """
    fpy.write("import warnings \nwarnings.filterwarnings('ignore')\n")
    fpy.write("\n")
    fpy.write("#Basic libraries\n")
    fpy.write("import os\n")
    fpy.write("import numpy as np\n")
    fpy.write("import pandas as pd\n")
    fpy.write("from pathlib import Path\n")
    fpy.write("from sklearn.model_selection import GroupShuffleSplit, RepeatedStratifiedKFold, LeaveOneOut\n")
    fpy.write("from sklearn.base import clone\n")
    fpy.write("from scipy.stats import mannwhitneyu, pearsonr\n")
    fpy.write("from stabl.visualization import scatterplot_features, boxplot_features\n")
    fpy.write("from stabl.stabl import Stabl, save_stabl_results\n")
    fpy.write("\n")
    fpy.write("from sklearn.linear_model import LassoCV, LogisticRegressionCV, LogisticRegression, LinearRegression, ElasticNetCV, Lasso\n")
    fpy.write("\n")
    fpy.write("#STABL pipelines\n")
    fpy.write("from stabl.multi_omic_pipelines import multi_omic_stabl, multi_omic_stabl_cv\n")
    fpy.write("from stabl.single_omic_pipelines import single_omic_stabl, single_omic_stabl_cv\n")
    fpy.write("\n") 
    fpy.write("#Preprocessing functions\n") 
    fpy.write("from sklearn.impute import SimpleImputer\n")
    fpy.write("from sklearn.pipeline import Pipeline\n")
    fpy.write("from sklearn.preprocessing import StandardScaler\n")
    fpy.write("from sklearn.feature_selection import VarianceThreshold\n")
    fpy.write("from stabl.preprocessing import LowInfoFilter, remove_low_info_samples\n")
    fpy.write("\n")